### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by pluvium27** [AuroraZiling/PipManager-legacy#3]
建议:
PIP 建议用 python -m pip 的方式调用, 或让用户设置调用命令, PIP 命令存在环境变量问题 (如在某些 Linux 发行版中, python3-pip 默认定义为 pip3, pip 指 python2-pip)

*ps: 请问这个是"科技与人文"杂志提到的 PIPManager 吗?*

**Comment by AuroraZiling** [comment]
你好！我archive这个仓库后才发现有issue（
emmm
这个建议我也发现了，但由于这个项目写的风格和现在我写的大有出入，导致难更新（屎山）
我会找时间制作重制版，将环境变量的问题解决（也有可能不做）

然后杂志提到的项目大概不是我这个，有可能是pypi里已经有的[PIP-Manager](https://pypi.org/project/pip-manager/)项目

感谢
